/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code;

import java.util.Arrays;
import suanfa.NewClass;

/**
 *
 * @author anlzou
 */
@SuppressWarnings("serial")
public class NewJFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        setVieFalse();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1_1 = new javax.swing.JTextField();
        jTextField1_3 = new javax.swing.JTextField();
        jTextField1_2 = new javax.swing.JTextField();
        jTextField3_1 = new javax.swing.JTextField();
        jTextField2_1 = new javax.swing.JTextField();
        jTextField4_1 = new javax.swing.JTextField();
        jTextField1_4 = new javax.swing.JTextField();
        jTextField1_5 = new javax.swing.JTextField();
        jTextField1_6 = new javax.swing.JTextField();
        jTextField1_7 = new javax.swing.JTextField();
        jTextField1_8 = new javax.swing.JTextField();
        jTextField1_9 = new javax.swing.JTextField();
        jTextField5_1 = new javax.swing.JTextField();
        jTextField6_1 = new javax.swing.JTextField();
        jTextField8_1 = new javax.swing.JTextField();
        jTextField7_1 = new javax.swing.JTextField();
        jTextField9_1 = new javax.swing.JTextField();
        jTextField2_2 = new javax.swing.JTextField();
        jTextField3_2 = new javax.swing.JTextField();
        jTextField4_2 = new javax.swing.JTextField();
        jTextField5_2 = new javax.swing.JTextField();
        jTextField6_2 = new javax.swing.JTextField();
        jTextField7_2 = new javax.swing.JTextField();
        jTextField8_2 = new javax.swing.JTextField();
        jTextField9_2 = new javax.swing.JTextField();
        jTextField2_3 = new javax.swing.JTextField();
        jTextField3_3 = new javax.swing.JTextField();
        jTextField4_3 = new javax.swing.JTextField();
        jTextField5_3 = new javax.swing.JTextField();
        jTextField6_3 = new javax.swing.JTextField();
        jTextField7_3 = new javax.swing.JTextField();
        jTextField8_3 = new javax.swing.JTextField();
        jTextField9_3 = new javax.swing.JTextField();
        jTextField2_4 = new javax.swing.JTextField();
        jTextField3_4 = new javax.swing.JTextField();
        jTextField4_4 = new javax.swing.JTextField();
        jTextField5_4 = new javax.swing.JTextField();
        jTextField6_4 = new javax.swing.JTextField();
        jTextField7_4 = new javax.swing.JTextField();
        jTextField8_4 = new javax.swing.JTextField();
        jTextField9_4 = new javax.swing.JTextField();
        jTextField3_5 = new javax.swing.JTextField();
        jTextField4_5 = new javax.swing.JTextField();
        jTextField5_5 = new javax.swing.JTextField();
        jTextField6_5 = new javax.swing.JTextField();
        jTextField7_5 = new javax.swing.JTextField();
        jTextField8_5 = new javax.swing.JTextField();
        jTextField9_5 = new javax.swing.JTextField();
        jTextField2_6 = new javax.swing.JTextField();
        jTextField3_6 = new javax.swing.JTextField();
        jTextField4_6 = new javax.swing.JTextField();
        jTextField5_6 = new javax.swing.JTextField();
        jTextField6_6 = new javax.swing.JTextField();
        jTextField7_6 = new javax.swing.JTextField();
        jTextField8_6 = new javax.swing.JTextField();
        jTextField9_6 = new javax.swing.JTextField();
        jTextField2_7 = new javax.swing.JTextField();
        jTextField3_7 = new javax.swing.JTextField();
        jTextField4_7 = new javax.swing.JTextField();
        jTextField5_7 = new javax.swing.JTextField();
        jTextField6_7 = new javax.swing.JTextField();
        jTextField7_7 = new javax.swing.JTextField();
        jTextField8_7 = new javax.swing.JTextField();
        jTextField9_7 = new javax.swing.JTextField();
        jTextField2_8 = new javax.swing.JTextField();
        jTextField3_8 = new javax.swing.JTextField();
        jTextField4_8 = new javax.swing.JTextField();
        jTextField5_8 = new javax.swing.JTextField();
        jTextField6_8 = new javax.swing.JTextField();
        jTextField7_8 = new javax.swing.JTextField();
        jTextField8_8 = new javax.swing.JTextField();
        jTextField9_8 = new javax.swing.JTextField();
        jTextField2_9 = new javax.swing.JTextField();
        jTextField3_9 = new javax.swing.JTextField();
        jTextField4_9 = new javax.swing.JTextField();
        jTextField5_9 = new javax.swing.JTextField();
        jTextField6_9 = new javax.swing.JTextField();
        jTextField7_9 = new javax.swing.JTextField();
        jTextField8_9 = new javax.swing.JTextField();
        jTextField9_9 = new javax.swing.JTextField();
        jTextField2_5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("n阶矩阵行列式计算器");
        setLocation(new java.awt.Point(500, 200));
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(java.awt.SystemColor.info);

        jLabel4.setText("矩阵A = ");

        jPanel2.setBackground(java.awt.SystemColor.info);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1_8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1_9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8_1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7_1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9_1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8_2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6_2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7_2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9_2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8_3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6_3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7_3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9_3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5_4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8_4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6_4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7_4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9_4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField5_5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField3_5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField4_5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField8_5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField6_5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField7_5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField9_5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5_6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3_6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2_6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4_6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8_6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6_6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7_6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9_6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5_7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3_7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2_7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4_7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8_7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6_7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7_7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9_7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5_8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3_8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2_8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4_8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8_8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6_8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7_8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9_8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5_9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3_9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2_9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4_9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8_9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6_9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7_9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9_9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField7_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField8_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField9_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField6_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField7_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField8_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField9_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField6_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField7_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField8_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField9_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField5_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField6_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField7_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField8_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField9_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jTextField3_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField5_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField6_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField7_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField8_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField9_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jTextField2_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField3_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField4_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField5_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField6_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField7_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField8_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField9_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jTextField2_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField3_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField4_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField5_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField6_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField7_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField8_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField9_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField2_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField5_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField6_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField7_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField8_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField9_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField2_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField5_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField6_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField7_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField8_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField9_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("计算");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("矩阵的行列式(|A|)=");

        jLabel2.setText("结果：");
        jLabel2.setToolTipText("");

        jButton2.setText("帮助");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("清除");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Welcome，欢迎");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2x2二阶矩阵", "3x3三阶矩阵", "4x4四阶矩阵", "5x5五阶矩阵", "6x6六阶矩阵", "7x7七阶矩阵", "8x8八阶矩阵", "9x9九阶矩阵" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        String text = (String) evt.getItem();
        jLabel3.setText(text + "行列式计算");
        String s = (String) evt.getItem(); 
        n = getItemIndex(s, n);
        setVieFalse();
        setVieFrue(n);
        setTextNull();
        jTextField1.setText("");
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void setTextNull() {
        if (n >= 1) {
            jTextField1_1.setText("");
            jTextField1_2.setText("");
            jTextField2_1.setText("");
            jTextField2_2.setText("");
        }
        if (n >= 2) {
            jTextField1_3.setText("");
            jTextField2_3.setText("");
            jTextField3_3.setText("");
            jTextField3_1.setText("");
            jTextField3_2.setText("");
        }
        if (n >= 3) {
            jTextField1_4.setText("");
            jTextField2_4.setText("");
            jTextField3_4.setText("");
            jTextField4_4.setText("");
            jTextField4_1.setText("");
            jTextField4_2.setText("");
            jTextField4_3.setText("");
        }
        if (n >= 4) {
            jTextField1_5.setText("");
            jTextField2_5.setText("");
            jTextField3_5.setText("");
            jTextField4_5.setText("");
            jTextField5_5.setText("");
            jTextField5_1.setText("");
            jTextField5_2.setText("");
            jTextField5_3.setText("");
            jTextField5_4.setText("");
        }
        if (n >= 5) {
            jTextField1_6.setText("");
            jTextField2_6.setText("");
            jTextField3_6.setText("");
            jTextField4_6.setText("");
            jTextField5_6.setText("");
            jTextField6_6.setText("");
            jTextField6_1.setText("");
            jTextField6_2.setText("");
            jTextField6_3.setText("");
            jTextField6_4.setText("");
            jTextField6_5.setText("");
        }
        if (n >= 6) {
            jTextField1_7.setText("");
            jTextField2_7.setText("");
            jTextField3_7.setText("");
            jTextField4_7.setText("");
            jTextField5_7.setText("");
            jTextField6_7.setText("");
            jTextField7_7.setText("");
            jTextField7_1.setText("");
            jTextField7_2.setText("");
            jTextField7_3.setText("");
            jTextField7_4.setText("");
            jTextField7_5.setText("");
            jTextField7_6.setText("");
        }
        if (n >= 7) {
            jTextField1_8.setText("");
            jTextField2_8.setText("");
            jTextField3_8.setText("");
            jTextField4_8.setText("");
            jTextField5_8.setText("");
            jTextField6_8.setText("");
            jTextField7_8.setText("");
            jTextField8_8.setText("");
            jTextField8_1.setText("");
            jTextField8_2.setText("");
            jTextField8_3.setText("");
            jTextField8_4.setText("");
            jTextField8_5.setText("");
            jTextField8_6.setText("");
            jTextField8_7.setText("");
        }
        if (n >= 8) {
            jTextField1_9.setText("");
            jTextField2_9.setText("");
            jTextField3_9.setText("");
            jTextField4_9.setText("");
            jTextField5_9.setText("");
            jTextField6_9.setText("");
            jTextField7_9.setText("");
            jTextField8_9.setText("");
            jTextField9_9.setText("");
            jTextField9_1.setText("");
            jTextField9_2.setText("");
            jTextField9_3.setText("");
            jTextField9_4.setText("");
            jTextField9_5.setText("");
            jTextField9_6.setText("");
            jTextField9_7.setText("");
            jTextField9_8.setText("");
        }
    }

    @SuppressWarnings("fallthrough")
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double value;
        double[][] jt = new double[n + 1][n + 1];
        jt = initSt(jt);//初始化数组
        value = NewClass.GetValue(jt, n + 1);
        jTextField1.setText(Double.toString(value));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        NewJDialog newJDialog = new NewJDialog(this, rootPaneCheckingEnabled);
        newJDialog.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setTextNull();
        jTextField1.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    @SuppressWarnings("fallthrough")
    private double[][] initSt(double jt[][]) {
        if (n >= 1) {
            jt[0][0] = Double.parseDouble(jTextField1_1.getText());
            jt[0][1] = Double.parseDouble(jTextField1_2.getText());
            jt[1][0] = Double.parseDouble(jTextField2_1.getText());
            jt[1][1] = Double.parseDouble(jTextField2_2.getText());
        }
        if (n >= 2) {
            jt[0][2] = Double.parseDouble(jTextField1_3.getText());
            jt[1][2] = Double.parseDouble(jTextField2_3.getText());
            jt[2][2] = Double.parseDouble(jTextField3_3.getText());
            jt[2][0] = Double.parseDouble(jTextField3_1.getText());
            jt[2][1] = Double.parseDouble(jTextField3_2.getText());
        }
        if (n >= 3) {
            jt[0][3] = Double.parseDouble(jTextField1_4.getText());
            jt[1][3] = Double.parseDouble(jTextField2_4.getText());
            jt[2][3] = Double.parseDouble(jTextField3_4.getText());
            jt[3][3] = Double.parseDouble(jTextField4_4.getText());
            jt[3][0] = Double.parseDouble(jTextField4_1.getText());
            jt[3][1] = Double.parseDouble(jTextField4_2.getText());
            jt[3][2] = Double.parseDouble(jTextField4_3.getText());
        }
        if (n >= 4) {
            jt[0][4] = Double.parseDouble(jTextField1_5.getText());
            jt[1][4] = Double.parseDouble(jTextField2_5.getText());
            jt[2][4] = Double.parseDouble(jTextField3_5.getText());
            jt[3][4] = Double.parseDouble(jTextField4_5.getText());
            jt[4][4] = Double.parseDouble(jTextField5_5.getText());
            jt[4][0] = Double.parseDouble(jTextField5_1.getText());
            jt[4][1] = Double.parseDouble(jTextField5_2.getText());
            jt[4][2] = Double.parseDouble(jTextField5_3.getText());
            jt[4][3] = Double.parseDouble(jTextField5_4.getText());
        }
        if (n >= 5) {
            jt[0][5] = Double.parseDouble(jTextField1_6.getText());
            jt[1][5] = Double.parseDouble(jTextField2_6.getText());
            jt[2][5] = Double.parseDouble(jTextField3_6.getText());
            jt[3][5] = Double.parseDouble(jTextField4_6.getText());
            jt[4][5] = Double.parseDouble(jTextField5_6.getText());
            jt[5][5] = Double.parseDouble(jTextField6_6.getText());
            jt[5][0] = Double.parseDouble(jTextField6_1.getText());
            jt[5][1] = Double.parseDouble(jTextField6_2.getText());
            jt[5][2] = Double.parseDouble(jTextField6_3.getText());
            jt[5][3] = Double.parseDouble(jTextField6_4.getText());
            jt[5][4] = Double.parseDouble(jTextField6_5.getText());
        }
        if (n >= 6) {
            jt[0][6] = Double.parseDouble(jTextField1_7.getText());
            jt[1][6] = Double.parseDouble(jTextField2_7.getText());
            jt[2][6] = Double.parseDouble(jTextField3_7.getText());
            jt[3][6] = Double.parseDouble(jTextField4_7.getText());
            jt[4][6] = Double.parseDouble(jTextField5_7.getText());
            jt[5][6] = Double.parseDouble(jTextField6_7.getText());
            jt[6][6] = Double.parseDouble(jTextField7_7.getText());
            jt[6][0] = Double.parseDouble(jTextField7_1.getText());
            jt[6][1] = Double.parseDouble(jTextField7_2.getText());
            jt[6][2] = Double.parseDouble(jTextField7_3.getText());
            jt[6][3] = Double.parseDouble(jTextField7_4.getText());
            jt[6][4] = Double.parseDouble(jTextField7_5.getText());
            jt[6][5] = Double.parseDouble(jTextField7_6.getText());
        }
        if (n >= 7) {
            jt[0][7] = Double.parseDouble(jTextField1_8.getText());
            jt[1][7] = Double.parseDouble(jTextField2_8.getText());
            jt[2][7] = Double.parseDouble(jTextField3_8.getText());
            jt[3][7] = Double.parseDouble(jTextField4_8.getText());
            jt[4][7] = Double.parseDouble(jTextField5_8.getText());
            jt[5][7] = Double.parseDouble(jTextField6_8.getText());
            jt[6][7] = Double.parseDouble(jTextField7_8.getText());
            jt[7][7] = Double.parseDouble(jTextField8_8.getText());
            jt[7][0] = Double.parseDouble(jTextField8_1.getText());
            jt[7][1] = Double.parseDouble(jTextField8_2.getText());
            jt[7][2] = Double.parseDouble(jTextField8_3.getText());
            jt[7][3] = Double.parseDouble(jTextField8_4.getText());
            jt[7][4] = Double.parseDouble(jTextField8_5.getText());
            jt[7][5] = Double.parseDouble(jTextField8_6.getText());
            jt[7][6] = Double.parseDouble(jTextField8_7.getText());
        }
        if (n >= 8) {
            jt[0][8] = Double.parseDouble(jTextField1_9.getText());
            jt[1][8] = Double.parseDouble(jTextField2_9.getText());
            jt[2][8] = Double.parseDouble(jTextField3_9.getText());
            jt[3][8] = Double.parseDouble(jTextField4_9.getText());
            jt[4][8] = Double.parseDouble(jTextField5_9.getText());
            jt[5][8] = Double.parseDouble(jTextField6_9.getText());
            jt[6][8] = Double.parseDouble(jTextField7_9.getText());
            jt[7][8] = Double.parseDouble(jTextField8_9.getText());
            jt[8][8] = Double.parseDouble(jTextField9_9.getText());
            jt[8][0] = Double.parseDouble(jTextField9_1.getText());
            jt[8][1] = Double.parseDouble(jTextField9_2.getText());
            jt[8][2] = Double.parseDouble(jTextField9_3.getText());
            jt[8][3] = Double.parseDouble(jTextField9_4.getText());
            jt[8][4] = Double.parseDouble(jTextField9_5.getText());
            jt[8][5] = Double.parseDouble(jTextField9_6.getText());
            jt[8][6] = Double.parseDouble(jTextField9_7.getText());
            jt[8][7] = Double.parseDouble(jTextField9_8.getText());
        }
        return jt;
    }

    private int getItemIndex(String s, int n) {
        switch (s) {
            case "2x2二阶矩阵":
                n = 1;
                break;
            case "3x3三阶矩阵":
                n = 2;
                break;
            case "4x4四阶矩阵":
                n = 3;
                break;
            case "5x5五阶矩阵":
                n = 4;
                break;
            case "6x6六阶矩阵":
                n = 5;
                break;
            case "7x7七阶矩阵":
                n = 6;
                break;
            case "8x8八阶矩阵":
                n = 7;
                break;
            case "9x9九阶矩阵":
                n = 8;
                break;
        }
        return n;
    }

    private void setVieFalse() {
        jTextField1_3.setVisible(false);
        jTextField2_3.setVisible(false);
        jTextField3_3.setVisible(false);
        jTextField3_1.setVisible(false);
        jTextField3_2.setVisible(false);
        jTextField1_4.setVisible(false);
        jTextField2_4.setVisible(false);
        jTextField3_4.setVisible(false);
        jTextField4_4.setVisible(false);
        jTextField4_1.setVisible(false);
        jTextField4_2.setVisible(false);
        jTextField4_3.setVisible(false);
        jTextField1_5.setVisible(false);
        jTextField2_5.setVisible(false);
        jTextField3_5.setVisible(false);
        jTextField4_5.setVisible(false);
        jTextField5_5.setVisible(false);
        jTextField5_1.setVisible(false);
        jTextField5_2.setVisible(false);
        jTextField5_3.setVisible(false);
        jTextField5_4.setVisible(false);
        jTextField1_6.setVisible(false);
        jTextField2_6.setVisible(false);
        jTextField3_6.setVisible(false);
        jTextField4_6.setVisible(false);
        jTextField5_6.setVisible(false);
        jTextField6_6.setVisible(false);
        jTextField6_1.setVisible(false);
        jTextField6_2.setVisible(false);
        jTextField6_3.setVisible(false);
        jTextField6_4.setVisible(false);
        jTextField6_5.setVisible(false);
        jTextField1_7.setVisible(false);
        jTextField2_7.setVisible(false);
        jTextField3_7.setVisible(false);
        jTextField4_7.setVisible(false);
        jTextField5_7.setVisible(false);
        jTextField6_7.setVisible(false);
        jTextField7_7.setVisible(false);
        jTextField7_1.setVisible(false);
        jTextField7_2.setVisible(false);
        jTextField7_3.setVisible(false);
        jTextField7_4.setVisible(false);
        jTextField7_5.setVisible(false);
        jTextField7_6.setVisible(false);
        jTextField1_8.setVisible(false);
        jTextField2_8.setVisible(false);
        jTextField3_8.setVisible(false);
        jTextField4_8.setVisible(false);
        jTextField5_8.setVisible(false);
        jTextField6_8.setVisible(false);
        jTextField7_8.setVisible(false);
        jTextField8_8.setVisible(false);
        jTextField8_1.setVisible(false);
        jTextField8_2.setVisible(false);
        jTextField8_3.setVisible(false);
        jTextField8_4.setVisible(false);
        jTextField8_5.setVisible(false);
        jTextField8_6.setVisible(false);
        jTextField8_7.setVisible(false);
        jTextField1_9.setVisible(false);
        jTextField2_9.setVisible(false);
        jTextField3_9.setVisible(false);
        jTextField4_9.setVisible(false);
        jTextField5_9.setVisible(false);
        jTextField6_9.setVisible(false);
        jTextField7_9.setVisible(false);
        jTextField8_9.setVisible(false);
        jTextField9_9.setVisible(false);
        jTextField9_1.setVisible(false);
        jTextField9_2.setVisible(false);
        jTextField9_3.setVisible(false);
        jTextField9_4.setVisible(false);
        jTextField9_5.setVisible(false);
        jTextField9_6.setVisible(false);
        jTextField9_7.setVisible(false);
        jTextField9_8.setVisible(false);
    }

    private void setVieFrue(int n) {
        switch (n) {
            case 8:
                jTextField1_9.setVisible(true);
                jTextField2_9.setVisible(true);
                jTextField3_9.setVisible(true);
                jTextField4_9.setVisible(true);
                jTextField5_9.setVisible(true);
                jTextField6_9.setVisible(true);
                jTextField7_9.setVisible(true);
                jTextField8_9.setVisible(true);
                jTextField9_9.setVisible(true);

                jTextField9_1.setVisible(true);
                jTextField9_2.setVisible(true);
                jTextField9_3.setVisible(true);
                jTextField9_4.setVisible(true);
                jTextField9_5.setVisible(true);
                jTextField9_6.setVisible(true);
                jTextField9_7.setVisible(true);
                jTextField9_8.setVisible(true);

            case 7:
                jTextField1_8.setVisible(true);
                jTextField2_8.setVisible(true);
                jTextField3_8.setVisible(true);
                jTextField4_8.setVisible(true);
                jTextField5_8.setVisible(true);
                jTextField6_8.setVisible(true);
                jTextField7_8.setVisible(true);
                jTextField8_8.setVisible(true);

                jTextField8_1.setVisible(true);
                jTextField8_2.setVisible(true);
                jTextField8_3.setVisible(true);
                jTextField8_4.setVisible(true);
                jTextField8_5.setVisible(true);
                jTextField8_6.setVisible(true);
                jTextField8_7.setVisible(true);
            case 6:
                jTextField1_7.setVisible(true);
                jTextField2_7.setVisible(true);
                jTextField3_7.setVisible(true);
                jTextField4_7.setVisible(true);
                jTextField5_7.setVisible(true);
                jTextField6_7.setVisible(true);
                jTextField7_7.setVisible(true);

                jTextField7_1.setVisible(true);
                jTextField7_2.setVisible(true);
                jTextField7_3.setVisible(true);
                jTextField7_4.setVisible(true);
                jTextField7_5.setVisible(true);
                jTextField7_6.setVisible(true);
            case 5:
                jTextField1_6.setVisible(true);
                jTextField2_6.setVisible(true);
                jTextField3_6.setVisible(true);
                jTextField4_6.setVisible(true);
                jTextField5_6.setVisible(true);
                jTextField6_6.setVisible(true);

                jTextField6_1.setVisible(true);
                jTextField6_2.setVisible(true);
                jTextField6_3.setVisible(true);
                jTextField6_4.setVisible(true);
                jTextField6_5.setVisible(true);
            case 4:
                jTextField1_5.setVisible(true);
                jTextField2_5.setVisible(true);
                jTextField3_5.setVisible(true);
                jTextField4_5.setVisible(true);
                jTextField5_5.setVisible(true);

                jTextField5_1.setVisible(true);
                jTextField5_2.setVisible(true);
                jTextField5_3.setVisible(true);
                jTextField5_4.setVisible(true);
            case 3:
                jTextField1_4.setVisible(true);
                jTextField2_4.setVisible(true);
                jTextField3_4.setVisible(true);
                jTextField4_4.setVisible(true);

                jTextField4_1.setVisible(true);
                jTextField4_2.setVisible(true);
                jTextField4_3.setVisible(true);
            case 2:
                jTextField1_3.setVisible(true);
                jTextField2_3.setVisible(true);
                jTextField3_3.setVisible(true);

                jTextField3_1.setVisible(true);
                jTextField3_2.setVisible(true);
            case 1:
                jTextField1_1.setVisible(true);
                jTextField1_2.setVisible(true);

                jTextField2_1.setVisible(true);
                jTextField2_2.setVisible(true);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField1_1;
    private javax.swing.JTextField jTextField1_2;
    private javax.swing.JTextField jTextField1_3;
    private javax.swing.JTextField jTextField1_4;
    private javax.swing.JTextField jTextField1_5;
    private javax.swing.JTextField jTextField1_6;
    private javax.swing.JTextField jTextField1_7;
    private javax.swing.JTextField jTextField1_8;
    private javax.swing.JTextField jTextField1_9;
    private javax.swing.JTextField jTextField2_1;
    private javax.swing.JTextField jTextField2_2;
    private javax.swing.JTextField jTextField2_3;
    private javax.swing.JTextField jTextField2_4;
    private javax.swing.JTextField jTextField2_5;
    private javax.swing.JTextField jTextField2_6;
    private javax.swing.JTextField jTextField2_7;
    private javax.swing.JTextField jTextField2_8;
    private javax.swing.JTextField jTextField2_9;
    private javax.swing.JTextField jTextField3_1;
    private javax.swing.JTextField jTextField3_2;
    private javax.swing.JTextField jTextField3_3;
    private javax.swing.JTextField jTextField3_4;
    private javax.swing.JTextField jTextField3_5;
    private javax.swing.JTextField jTextField3_6;
    private javax.swing.JTextField jTextField3_7;
    private javax.swing.JTextField jTextField3_8;
    private javax.swing.JTextField jTextField3_9;
    private javax.swing.JTextField jTextField4_1;
    private javax.swing.JTextField jTextField4_2;
    private javax.swing.JTextField jTextField4_3;
    private javax.swing.JTextField jTextField4_4;
    private javax.swing.JTextField jTextField4_5;
    private javax.swing.JTextField jTextField4_6;
    private javax.swing.JTextField jTextField4_7;
    private javax.swing.JTextField jTextField4_8;
    private javax.swing.JTextField jTextField4_9;
    private javax.swing.JTextField jTextField5_1;
    private javax.swing.JTextField jTextField5_2;
    private javax.swing.JTextField jTextField5_3;
    private javax.swing.JTextField jTextField5_4;
    private javax.swing.JTextField jTextField5_5;
    private javax.swing.JTextField jTextField5_6;
    private javax.swing.JTextField jTextField5_7;
    private javax.swing.JTextField jTextField5_8;
    private javax.swing.JTextField jTextField5_9;
    private javax.swing.JTextField jTextField6_1;
    private javax.swing.JTextField jTextField6_2;
    private javax.swing.JTextField jTextField6_3;
    private javax.swing.JTextField jTextField6_4;
    private javax.swing.JTextField jTextField6_5;
    private javax.swing.JTextField jTextField6_6;
    private javax.swing.JTextField jTextField6_7;
    private javax.swing.JTextField jTextField6_8;
    private javax.swing.JTextField jTextField6_9;
    private javax.swing.JTextField jTextField7_1;
    private javax.swing.JTextField jTextField7_2;
    private javax.swing.JTextField jTextField7_3;
    private javax.swing.JTextField jTextField7_4;
    private javax.swing.JTextField jTextField7_5;
    private javax.swing.JTextField jTextField7_6;
    private javax.swing.JTextField jTextField7_7;
    private javax.swing.JTextField jTextField7_8;
    private javax.swing.JTextField jTextField7_9;
    private javax.swing.JTextField jTextField8_1;
    private javax.swing.JTextField jTextField8_2;
    private javax.swing.JTextField jTextField8_3;
    private javax.swing.JTextField jTextField8_4;
    private javax.swing.JTextField jTextField8_5;
    private javax.swing.JTextField jTextField8_6;
    private javax.swing.JTextField jTextField8_7;
    private javax.swing.JTextField jTextField8_8;
    private javax.swing.JTextField jTextField8_9;
    private javax.swing.JTextField jTextField9_1;
    private javax.swing.JTextField jTextField9_2;
    private javax.swing.JTextField jTextField9_3;
    private javax.swing.JTextField jTextField9_4;
    private javax.swing.JTextField jTextField9_5;
    private javax.swing.JTextField jTextField9_6;
    private javax.swing.JTextField jTextField9_7;
    private javax.swing.JTextField jTextField9_8;
    private javax.swing.JTextField jTextField9_9;
    // End of variables declaration//GEN-END:variables
    int n = 1;
}
